name: h_c_1

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  go_router: ^14.6.3
  shared_preferences: ^2.3.5
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/imagenes/san-miguel.png
    - assets/imagenes/adult.png
    - assets/imagenes/nino.png
    - assets/imagenes/historia-clinica.png
    - assets/imagenes/voz.png
    - assets/imagenes/icono.png
    - assets/imagenes/buscar.png
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconoApp/iconApp.png"  # Ruta del ícono
  adaptive_icon_foreground: "assets/iconoApp/iconApp.png"
  adaptive_icon_background: "#ffffff"
