sonar.organization=carlos-lopez-c
sonar.projectKey=carlos-lopez-c_FinalTesisAPP
sonar.projectName=FinalTesisAPP
sonar.host.url=https://sonarcloud.io
sonar.sources=lib
sonar.tests=test
sonar.coverage.exclusions=**/*.g.dart,**/*.freezed.dart
sonar.cpd.exclusions=**/*.g.dart,**/*.freezed.dart
sonar.sourceEncoding=UTF-8
