name: SonarQube Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: windows-latest  # o ubuntu-latest si prefieres Linux
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para un análisis correcto en SonarQube
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token generado en SonarCloud
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Necesario para integración con GitHub
