name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Paso OPCIONAL para Java (solo si usas Maven)
      # - name: Build with Maven
      #   if: contains(github.event.pull_request.labels.*.name, 'java')  # Ejemplo condicional
      #   run: |
      #     cd ruta/al/pom.xml  # Especifica la ruta si está en subdirectorio
      #     mvn clean verify -B -DskipTests

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=FinalTesisAPP
            -Dsonar.organization=carlos-lopez-c
            -Dsonar.branch.name=main
            -Dsonar.qualitygate.wait=true
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=./src  # Ajusta esta ruta según tu estructura
